### ISSUE TITLE
Copy beatmap link to clipboard

### ISSUE THREAD

**Issue by Renzu96** [Piotrekol/CollectionManager#1]
This is a feature request. It would be nice if there's an option to copy beatmap set or individual difficulty link to clipboard on context menu. I've been using this program since it's early version and I noticed that there was something like "Copy as text" option before it's removed in the latest release so I think it's quite possible to add this feature.
I wish I can contribute to this project but I have limited knowledge about C# / Visual Studio programming (I'd love to learn though).

**Comment by Piotrekol** [comment]
Ask and you shall receive ;)
It should output maps in exactly same format as in previous versions, however I am open for suggestions.

**Comment by Renzu96** [comment]
I managed to build your latest commit using Mono (I don't have Microsoft Visual Studio installed, lol) and the "Copy as text" option is back indeed. However, it's still not fulfill the requested feature since it's copying the beatmap name, difficulty and star rating instead of the beatmap URL.
By the way, I use this [IRCAutoHost](https://github.com/tsbreuer/IRCAutoHost) and it requires beatmap URL to run it's command. I think it would be great to use it alongside with CollectionManager since I can't open song selection in AutoHost's lobby. (I hope you get the idea)

**Comment by Piotrekol** [comment]
So would adding beatmap url to "Copy as text" output be sufficient?

**Comment by Renzu96** [comment]
It would be better if there's separate option on the context menu (i.e. "Copy beatmap URL") which only output the beatmap URL (i.e. http://osu.ppy.sh/b/<beatmapID>). Just like when you right click on link in web browser.

**Comment by Piotrekol** [comment]
You should now be able to copy beatmap links from new menu option.

**Comment by Renzu96** [comment]
Whoa, so fast. And it works!
Thanks a lot, Piotrekol! Keep up the good work! :smile: :+1:
