### ISSUE TITLE
Save > Collections in separate files not working

### ISSUE THREAD

**Issue by Aidan-Kerr** [Piotrekol/CollectionManager#13]
Title. Working on a big set of collections (Grouping all OWC Maps by Stage, Mod and Year) and it's not working. I can delete all other collections and then save the collections individually before reloading collections and repeating, but since I have about 350 collections I have to save I'd understandably rather not. It would be great if you could help me diagnose and fix the issue!

**Comment by Piotrekol** [comment]
Fixed, was generating invalid file path and collection filenames
prerelease download is available here https://ci.appveyor.com/api/buildjobs/n1ydw11doir8uja6/artifacts/InnoSetup%2Foutput%2FCollectionManagerSetup.exe
