### ISSUE TITLE
[Enhancement/Suggestion] Generate collections based on osu! search querys

### ISSUE THREAD

**Issue by flleeppyy** [Piotrekol/CollectionManager#17]
I'd like to suggest the ability to generate collections by entering in a search term like you would in osu!, and all the beatmaps that contain that search term, it would add to the collection

This would be very useful for those who want a ton of beatmap by a certain artist, or a certain genre, all in a collection, especially if they have a ton of beatmaps and don't feel like manually adding them to collections, one by one.

**Comment by Piotrekol** [comment]
create new empty collection
Open beatmap listing
search for what you want
select all (Ctrl+a) and drag maps from beatmap listing onto your collection in main window.

Am I missing something?

**Comment by flleeppyy** [comment]
I am so dumb
