### ISSUE TITLE
Versions 1.0.148, and 1.0.145 not working for me.

### ISSUE THREAD

**Issue by Yoteosu** [Piotrekol/CollectionManager#19]
I was trying to use it, and those versions instantly close. I'm on Windows 10 and I'm curious if there is anything I can do to fix it? Version 1.0.140 works completely fine though.

**Comment by Piotrekol** [comment]
the only thing that changed between current and 140 at startup is the requirement to have valid scores.db in osu! directory(and now that I think of it, it should be optional). But even if you are missing scores.db it should still result in (visible) crash...

https://github.com/piotrekol/collectionmanager/compare/1.0.140...1.0.148

**Comment by Piotrekol** [comment]
After checking out relevant scores.db there is new (now documented) value in file with appears only when TP is active.
Fixed in 2e4a80f553da099918f6a1f8435f9f532052e9ed
