### ISSUE TITLE
[Feature request] Pressing F2 renames a colletion

### ISSUE THREAD

**Issue by syyyr** [Piotrekol/CollectionManager#20]
It is common that F2 usually means "Rename" in Windows (in Explorer for example). I'd like a feature, where F2 brings up the dialog for renaming the selected collection.

I tried to look into the code, but I don't know where such a thing could be implemented, Windows programming is too much for me, sorry.

Thanks

**Comment by Piotrekol** [comment]
Done in 0d3ae0c255c97239af1a3741485d862d8aefb702

**Comment by syyyr** [comment]
Thanks!
