### ISSUE TITLE
Not downloading missing maps 

### ISSUE THREAD

**Issue by DrowsyOsu** [Piotrekol/CollectionManager#22]
When i try to download missing maaps it says "you don't have any missing maps that CM is able to download". My friend is also having the same problem, am i missing something?

**Comment by MathisBicheyre** [comment]
same

**Comment by Piotrekol** [comment]
collections loaded from .db files do not contain enough information to be able to download these maps. For that, you need .osdb collection file generated by a user(owner of that .db file) that has these maps.
If that's not an option you can also try uploading that file to https://osustats.ppy.sh/collections with will find the majority of these maps and create .osdb files for you.
