### ISSUE TITLE
i have questions about this program

### ISSUE THREAD

**Issue by apple1367** [Piotrekol/CollectionManager#23]
First of all, I want to say that I am sorry for using the issue window as a personal question.

I am trying to make an advanced osu difficulty calculater in Python, but I want to know how to add a bitmap with the difficulty calculations completed to the collection.

On the osu official website, MD5 hash is used, but as a result of opening collections and db directly, I could not decrypt it.

So, I want to know osu's collection algorithm.

I want to know how to add to a collection and how to create a new collection.

I can get All information that can be gained by opening the .osu file such as the bitmap title and bitmap ID 

Thank you for reading the low-quality question translated by the translator.
I would be grateful if you gave me an answer.

**Comment by Piotrekol** [comment]
I'm pretty sure you already figured this out, but osu collection.db is a binary blob. It is not encrypted.
collection.db format spec is available here https://osu.ppy.sh/wiki/en/osu%21_File_Formats/Db_%28file_format%29#collection.db
