### ISSUE TITLE
mapID 0 issue

### ISSUE THREAD

**Issue by Voider404** [Piotrekol/CollectionManager#26]
For quite the long time i have this issue, where if you add graveyarded map to collection and open same collection with CM, i get mapId: 0. Is there any way that this issue could be fixed?
Note: This bug isn't on all maps, for some reason.

**Comment by FuchsPlayZ** [comment]
This might be becaus of

1. Not-Updated Maps
2. Non-Uploaded Maps
3. Broken Maps

Try Refreshing your Maps and or Updating them. This might fixes it. gl
