### ISSUE TITLE
No Instructions or Tutorial.

### ISSUE THREAD

**Issue by onlyatroller** [Piotrekol/CollectionManager#27]
Seeing as this software is pretty unintuitive, You should add some instructions to help out new users. It also seems that the "Tutorial" link on the osu!forums doesnt work anymore, so you should update that aswell. Thanks

**Comment by Piotrekol** [comment]
for whatever reason, gist link for "tutorial" has changed. This is the current link with is now also updated in osu! thread: https://gist.github.com/Piotrekol/2446c84030d74eab02bc8f29dd5548b7
