### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YSPESHNUY** [Piotrekol/CollectionManager#28]
At first, everything worked fine, but then the program just started to crash everytime, when I just "touch" the map. I click only once, if that matter

https://user-images.githubusercontent.com/79416318/108633357-e7e54700-7484-11eb-8a55-d89f78124eeb.mp4

**Comment by Piotrekol** [comment]
Are you using custom songs location in osu! or are all your songs in `C:\osu!\Songs`?

**Comment by YSPESHNUY** [comment]
> Are you using custom songs location in osu! or are all your songs in `C:\osu!\Songs`?
All in osu songs
> also, check event viewer - right after crash there should be `Information` event in `Windows Logs->Application` with basic crash info from `App.exe`
![image](https://user-images.githubusercontent.com/79416318/108634255-d6eb0480-7489-11eb-94cc-e9dd02c268bf.png)
I guess this..?

**Comment by YSPESHNUY** [comment]
Or maybe this
![image](https://user-images.githubusercontent.com/79416318/108638272-736bd180-749f-11eb-8d64-aab6f2599606.png)

**Comment by Piotrekol** [comment]
Install this and paste exception text here: https://ci.appveyor.com/api/buildjobs/iofi65rhnew9wry4/artifacts/InnoSetup%2Foutput%2FCollectionManagerSetup.exe

**Comment by YSPESHNUY** [comment]
B = "in" here, I guess
---------------------------
Error
---------------------------
There was a problem with CollectionManager and it needs to exit, exception text was copied to your clipboard:

System.IO.FileNotFoundException: Файл 'C:\osu!\Songs\etterna solo files\etterna solo files\(Xiaounlimited) #1 Route\- #1 Route [Hard(dance-solo)] ().osu' не найден. (File is not found)

Имя файла(file name): 'C:\osu!\Songs\etterna solo files\etterna solo files\(Xiaounlimited) #1 Route\- #1 Route [Hard(dance-solo)] ().osu'

   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   в System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)

   в System.IO.StreamReader..ctor(String path)

   в CollectionManagerExtensionsDll.Utils.BeatmapUtils.GetImageLocation(Beatmap beatmap)

   в App.Presenters.Controls.BeatmapThumbnailPresenter.LoadData(BeatmapExtension beatmap)

   в App.Presenters.Controls.BeatmapThumbnailPresenter._model_BeatmapChanged(Object sender, EventArgs e)

   в App.Presenters.Controls.CombinedBeatmapPreviewPresenter.ModelOnBeatmapChanged(Object sender, EventArgs eventArgs)

   в GuiComponents.Controls.BeatmapListingView.<Bind>b__34_1(Object _, EventArgs __)

   в BrightIdeasSoftware.ObjectListView.OnSelectionChanged(EventArgs e)

   в System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)

   в System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   в System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   в System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   в System.Windows.Forms.Form.ShowDialog(IWin32Window owner)

   в GuiComponents.Forms.BaseForm.ShowAndBlock()

   в App.Initalizer.Run(String[] args)

   в App.Program.Main(String[] args)
---------------------------
ОК   
---------------------------

**Comment by Piotrekol** [comment]
it looks like your osu!.db is corrupted and contains map entries that do not exist anymore on your disk.
While I fixed this particular problem just to allow browsing/editing thru these beatmaps anyway, I recommend opening osu and reprocessing your beatmaps by pressing CTRL+F5 in song selection.

https://ci.appveyor.com/api/buildjobs/fxobad2wlf21e054/artifacts/InnoSetup%2Foutput%2FCollectionManagerSetup.exe

**Comment by YSPESHNUY** [comment]
Works fine now, thanks!
