### ISSUE TITLE
Opening suspended and closes

### ISSUE THREAD

**Issue by nethersonic** [Piotrekol/CollectionManager#29]
![rfgesd](https://user-images.githubusercontent.com/79421147/108636983-b0f83c80-7456-11eb-94db-9415af68d211.png)

idk what happens ive re installed and ran it as an admin but it just opens and closes on its own

**Comment by Piotrekol** [comment]
Install this and paste exception text here: https://ci.appveyor.com/api/buildjobs/iofi65rhnew9wry4/artifacts/InnoSetup%2Foutput%2FCollectionManagerSetup.exe

**Comment by Koltay** [comment]
![image](https://user-images.githubusercontent.com/73950784/109728355-fa801e80-7bf0-11eb-9b04-310b5341587f.png)
I have the same issue while saving collection and downloading beatmaps, hope this could help solving

**Comment by Just-A-Shrimp** [comment]
I also have the same issue. I installed the app properly, tried opening it then it would stop working. 
![Error](https://user-images.githubusercontent.com/82657077/115023838-e3bc2f80-9ef1-11eb-9930-8c7cc046875c.png)

**Comment by Piotrekol** [comment]
original author never responded
