### ISSUE TITLE
Opening the app and then suddenly closing

### ISSUE THREAD

**Issue by Just-A-Shrimp** [Piotrekol/CollectionManager#30]
Whenever I try to open the app it closes and then shows me this error(Im using windows 7). 
![Error (2)](https://user-images.githubusercontent.com/82657077/115501725-4f155100-a2a6-11eb-99a1-9270ca320441.png)

**Comment by Piotrekol** [comment]
is this still happening? Have you tried running NET repair tool? https://www.microsoft.com/en-us/download/details.aspx?id=30135
