### ISSUE TITLE
(Feature Request-ish) adding beatmaps to collection via md5

### ISSUE THREAD

**Issue by cptslow-osu** [Piotrekol/CollectionManager#33]
ik this is a stretch but afaik this is the only way to contact you aside from osu ingame pm and this is probably the best place to contact you about something collection related:
i have a [spreadsheet ](https://docs.google.com/spreadsheets/d/1yqIwNWpAWUzi-abfmQBYxh3wDfZAKbagb9aWMzadi8k/edit#gid=0)with all maps from badged tournaments in 2020 which contains map md5, mod (collection name) and id. 

It would be fantastic if you added a feature that allowed bulk adding maps to collections via md5. (as in when rightclicking inside of a collection inside of collection manager you have a bulk add menu option or adding bulk md5 to the generate dialogue)

obviously this is an extremely niche use case so if that's too much work for something that probably just me will end up using, I'd greatly appreciate if you were able to point me in the right direction on what I need to write such a tool myself. 

Thanks in advance :)

**Comment by Piotrekol** [comment]
What you are requesting is pretty much what this unfinished piece of code does https://github.com/Piotrekol/CollectionManager/blob/master/App/SidePanelActionsHandler.cs#L303-L362. It allows users to import beatmaps using either mapIds or map hashes, but currently it completely lacks UI(2 forms) and thus is inaccessible without code edits.

I might finish this sometime this month(do not take this as ETA).

As for contacting me, there's also discord dedicated to osu applications I'm maintaining https://discord.gg/N854wYZ

**Comment by Piotrekol** [comment]
cabe888847841a01f97e683e5cda17c964aa8af1 added ability to generate collections from a list/file containing a list of beatmapIds. However, you do have to have all beatmaps locally. If you do not, these will have to be uploaded to osustats for it to fill rest of the data.
