### ISSUE TITLE
Cannot update existing collection from osustats after adding more songs to collection.

### ISSUE THREAD

**Issue by TheFantasticLoki** [Piotrekol/CollectionManager#34]
Title is self explanatory. just upload a collection then modify it ingame reload collections manager and go to osustats collections, your collections and try uploading changes.

**Comment by TheFantasticLoki** [comment]
![image](https://user-images.githubusercontent.com/26889568/126603297-61adb513-1808-402d-a848-39917f8d20fb.png)

**Comment by Piotrekol** [comment]
sadly I'm not able to reproduce this at all https://streamable.com/ffkhcq
mind providing exact reproduction steps?
