### ISSUE TITLE
Missing Beatmaps

### ISSUE THREAD

**Issue by spookedlul** [Piotrekol/CollectionManager#37]
When making a collection I only had about 1/3 of the maps so I checked and about two thirds of the maps that are supposed to be there say "No data - 9b322062f692fc65dd8cb138fe18c251," or some other random string of letters and numbers, I was wondering what I am supposed to do about that?

**Comment by Piotrekol** [comment]
copied from discord:
```
maps can appear as "no data - abcd..." due to:
- you loading .db file instead of .osdb
- user that created specific .osdb file didn't have these maps either
- since adding these maps to your collections, you updated these maps ingame.. with osu! doesn't handle - this effectively removes these maps from all collections. But since old data is still there, these show up as unknown 
```
