### ISSUE TITLE
Can't compile on linux 

### ISSUE THREAD

**Issue by af2111** [Piotrekol/CollectionManager#39]
When trying to compile this on linux, it gives this error: /usr/share/dotnet/sdk/5.0.205/Microsoft.Common.CurrentVersion.targets(3136,5): error : ResGen.exe not supported on .NET Core MSBuild [/home/af2111/Downloads/CollectionManager/ObjectListView/ObjectListView2012.csproj]

Is there a way to fix this?

**Comment by Piotrekol** [comment]
While side projects do support .net standard builds, main application and optimized list implementation that it is using depends on old version of .NET with can not be easily updated to NET5+.

There are currently no plans to upgrade to .net version beyond 4.8

what is the issue that you are trying to fix by recompiling?

**Comment by af2111** [comment]
none, I just want to run this program on linux.
