### ISSUE TITLE
"Access Denied" When trying to save collections to osu! collection

### ISSUE THREAD

**Issue by CraftH** [Piotrekol/CollectionManager#44]
I've been trying to save my collections for a while now and it keeps giving me the same error. I have tried opening the Collection Manager as Administrator but when I try to save my collections it tells me "Please close osu! before saving your collections", I checked the Task Manager and osu isn't open. What do I do? 
![image](https://user-images.githubusercontent.com/95979025/145686933-77b3280f-78e4-4b91-8ecc-a406db303236.png)

**Comment by Piotrekol** [comment]
do you have any other process running that is called just `osu!`?

**Comment by CraftH** [comment]
> do you have any other process running that is called just `osu!`?

No, I dont

**Comment by Piotrekol** [comment]
I would triple check that you are not running osu! as administrator and that it is indeed not running.
Still, if you're sure that is not the case grab a build from the commit referenced above that contains a workaround
