### ISSUE TITLE
CollectionManager Crashes Immediately after Opening

### ISSUE THREAD

**Issue by chezbananas** [Piotrekol/CollectionManager#54]
ran the Linux installer with wine (on manjaro with linux 5.16.2), and the program crashes a few seconds after opening -- no GUI is shown, but the icon shows up in the taskbar for a bit. is there an alternate method of installation/any other helpful information I could provide? thank you.

**Comment by Piotrekol** [comment]
Make sure to use `_linux.exe` setup. It was created to allow running CM under wine due to some shortcomings on their side.
I haven't tested it myself but users have confirmed it running in the past with 6.11/6.20 wine + net472
