### ISSUE TITLE
[FETURE REQUEST] Have the option to split a collection into multiple smaller collections

### ISSUE THREAD

**Issue by yeahirai** [Piotrekol/CollectionManager#68]
So i use this aplication called osu!collector which uses collections to create map packs to download and share with other people. The problem is that it limits to only 2000 maps per collection. To fit these requirements i use osu collector to make reduce my collection sizes to smaller version but thats a lot of work to when i have many colletions to work with. Therefore i think it would be useful to have a way to create these smaller versions automatically.

My first idea was that it work like this: select one or more collections, click a split button, then select if it would either be split into multiples colletions of the same size or into colections of a set maximum size.

**Comment by Kuuuube** [comment]
Have you considered uploading to https://osustats.ppy.sh/collections instead? It has a **much** higher limit. There are integrations in CM as well and you can download maps through CM too.

You may also want to ask the osu!collector devs to increase the map limit. 2000 maps is pitifully low.

This request isn't insane to implement but it just seems like the wrong solution.

**Comment by Piotrekol** [comment]
This feature request is specific to osu!collector behavior of limiting collections to 2k maps. Outside of that use case, I do not see it ever being useful.
