### ISSUE TITLE
Cannot enter my osu! folder location on Linux. (Arch Linux)

### ISSUE THREAD

**Issue by noemsus** [Piotrekol/CollectionManager#71]
Hello, am using Linux and when I'm clicking "Load beatmaps from different location" and I cannot enter my osu! location, because it's a hidden folder (.local) like AppData on Windows. And please make the Linux version better thx. Am using arch btw.

**Comment by TheOnlyPhoenix** [comment]
You need to enable view hidden files in your wineprefix. Do this by running `WINEPREFIX=~/.local/<yourwineprefix> winetricks`, then click `Select the default wineprefix` in the dialogue, then `Run winecfg`. Once the wine window opens, go to `Drives` and enable `Show dot files`.
