### ISSUE TITLE
Question: What is 'onlineId' in the 'OsdbCollectionHandler' class

### ISSUE THREAD

**Issue by waylaa** [Piotrekol/CollectionManager#79]
This value is required in o!dm7 (or higher) collections and i would like to ask what is it exactly. I am sure it can't be the id of a beatmap or beatmapset since those values are already written afterwards in a collection.

**Comment by Piotrekol** [comment]
Id of the collection on https://osustats.ppy.sh/collections if it was downloaded from there. Left as 0 if not.

https://github.com/Piotrekol/CollectionManager/blob/master/CollectionManagerDll/DataTypes/ICollection.cs#L49-L52

**Comment by omkelderman** [comment]
I use -1 in https://cm-favs-generator.omkserver.nl/ :eyes:

**Comment by waylaa** [comment]
> Id of the collection on https://osustats.ppy.sh/collections if it was downloaded from there. Left as 0 if not.
> 
> https://github.com/Piotrekol/CollectionManager/blob/master/CollectionManagerDll/DataTypes/ICollection.cs#L49-L52

Okay so if i generate my own collections locally, I just put 0 then. Thanks for the answer.
