### ISSUE TITLE
Every song in collection shows up as unknown, no matter what collection I try

### ISSUE THREAD

**Issue by catgirlmekk** [Piotrekol/CollectionManager#86]
I reset my pc a couple hours ago and need to download a bunch of maps and its just easy to do it through CM but when I import any .db file, every single map shows up as unknown unless its already installed.
![image](https://github.com/user-attachments/assets/01e1238d-b7e2-429a-bfd9-7763436c906f)

**Comment by Piotrekol** [comment]
see https://github.com/Piotrekol/CollectionManager#collection-file-formats
