### ISSUE TITLE
cannot search for mania keys

### ISSUE THREAD

**Issue by qusteka** [Piotrekol/CollectionManager#9]
mode=m stars>=1.63 status=r keys=4
or 
mode=m stars>=1.63 status=r cs=4 

yield 0 results on thousands of maps

**Comment by Piotrekol** [comment]
Works only for native osu!Mania maps - currently I have no idea how to calc converted keys.

**Comment by LastExceed** [comment]
Getting the key count for converts requires actually converting the map. Even the osu! client doesn't include converts in the search. If you search for `keys=4` in osu! it will only show native mania maps, as if you had searched for `keys=4 mode=m`. It'd be perfectly fine for CollectionManager to have the same behavior.

**Comment by qusteka** [comment]
Hi, sorry for the late reply. Tbh I had forgotten about this thread. The thing: is it didn't yield any results on native mania maps either, wasn't searching on converts.

**Comment by LastExceed** [comment]
@qusteka that was fixed in the referenced commit Piotrekol@7f180a168023e96718d44889d793d18682b83bb4 which you can see right below your initial message

**Comment by qusteka** [comment]
@LastExceed Thanks, I was unaware of that!
